/// Backend BC — the only place in the application that talks to
/// `libllama.dylib`.
///
/// ## Responsibility
///
/// Wraps the llama.cpp C ABI through the Foreign Function & Memory API.
/// Owns the lifecycle of a loaded model (weights + vocab) and of a decoding
/// session (KV cache, batch decode, sampler-driven token emission). Every
/// other BC works against the Java types exposed here and never allocates
/// a `MemorySegment` or opens an `Arena`.
///
/// ## Threading
///
/// llama.cpp contexts are not thread-safe. No internal locking — callers
/// serialize access. The HTTP front-end runs on a single-threaded executor
/// for exactly this reason.
///
/// ## FFM bindings
///
/// The jextract output for `llama.h` lives in a sub-package and is treated
/// as a vendored binding, regenerated by `src/main/scripts/jextract.sh`. No
/// business logic ever lives there.
package lm.backend;
